import type { Item } from '../types';

export const seedItems: Item[] = [
  {
    id: 'seed-1',
    title: 'Interior Door Security Windows',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Security', 'Building'],
    assignedTo: "Art Craddock, Men's Group",
    firstRaisedDate: '2025-10-01',
    notes: "Moved to men's group work list. Two installed, two more to order.",
  },
  {
    id: 'seed-2',
    title: 'Handicap Parking Signs',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Accessibility', 'Grounds'],
    assignedTo: "Art Craddock, Men's Group",
    firstRaisedDate: '2025-10-21',
    notes: "Signs and posts in hand, moved to men's group work list.",
  },
  {
    id: 'seed-3',
    title: 'Handicap Rails in Restrooms',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Accessibility', 'Building'],
    assignedTo: "Scott Bragg, Men's Group",
    firstRaisedDate: '2025-10-21',
    notes:
      "9 sets of 24-inch grab bars needed (6 main + 1 behind sanctuary + 2 children's wing). Rails purchased, not yet installed.",
  },
  {
    id: 'seed-4',
    title: 'First Aid Kits',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['SafetySanctuary'],
    assignedTo: 'Art Craddock, Cynthia',
    firstRaisedDate: '2025-10-01',
    notes: 'No update at last meeting. Art following up.',
  },
  {
    id: 'seed-5',
    title: 'LED Lighting and Thermostats',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building', 'Technology'],
    assignedTo: 'Art Craddock',
    firstRaisedDate: '2025-10-01',
    notes: 'Matrix ES / Gary Horton unresponsive. ~20 lights + thermostats remaining.',
  },
  {
    id: 'seed-6',
    title: "Children's Wing Furniture Disposal",
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Furniture', 'Building'],
    assignedTo: 'Joey Skinner',
    firstRaisedDate: '2025-10-21',
    notes:
      'Plan: sell at yard sale (first weekend of May), then free pickup, then dispose. Ghana donation declined ($4K shipping not feasible).',
  },
  {
    id: 'seed-7',
    title: 'Doorbell Camera (Front Office)',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Security', 'Technology'],
    assignedTo: 'Bart Arther, Mike Davis',
    firstRaisedDate: '2025-10-21',
    notes: 'Camera in hand, installation targeted in coming weeks.',
  },
  {
    id: 'seed-8',
    title: 'CE Mitchell Tutoring Program',
    status: 'Open',
    standing: true,
    defaultSection: 'Update',
    tags: ['FacilityUse'],
    assignedTo: 'Jane Carter, Pat Smith',
    firstRaisedDate: '2025-10-01',
    notes: 'Running well. Mon/Tue/Thu 5-6 PM.',
  },
  {
    id: 'seed-9',
    title: "Children's Wing Carpet Cleaning",
    status: 'Tabled',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building', 'Grounds'],
    assignedTo: 'Art Craddock',
    firstRaisedDate: '2025-10-21',
    onHoldReason: 'Tabled pending decision on clean vs. replace with hard flooring.',
    notes: 'Quotes on file: Squeaky Clean $749, ANAGO $951.25. Last discussed Mar 2026.',
  },
  {
    id: 'seed-10',
    title: 'Fellowship Hall Chairs (Donation)',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Furniture', 'Building'],
    assignedTo: 'Bart Arther',
    firstRaisedDate: '2026-01-20',
    notes:
      "NPS 8500 samples arrived; comfortable but plastic glides scratch LVP. Donor committed ~120; board wants 160 (4x40 packs, ~$11,860 Sam's Club). Glide problem must be resolved before bulk order.",
  },
  {
    id: 'seed-11',
    title: 'Chapel Awning',
    status: 'Tabled',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: 'Julian Carter',
    firstRaisedDate: '2026-01-20',
    onHoldReason: 'On hold pending cash position. Revisit Jun/Jul.',
    deferredUntil: '2026-06-01',
    notes: 'Extreme Images quote $1,712 approved Mar 2026 but not yet executed.',
  },
  {
    id: 'seed-12',
    title: "Pastor's Office Carpet",
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: 'Pastor Thomas Long',
    firstRaisedDate: '2026-01-20',
    notes:
      "Carpet tile approach under investigation. Waiting on Buddy Laughridge's contacts. Room ~17ft square; carpet rolls 12ft wide so tiles preferred. Donated funds available.",
  },
  {
    id: 'seed-13',
    title: 'Harness Capital Campaign (HVAC Fundraising)',
    status: 'Open',
    standing: true,
    defaultSection: 'Update',
    tags: ['HVAC', 'Budget'],
    assignedTo: 'Scott Bragg',
    firstRaisedDate: '2026-01-20',
    notes:
      'CD funds released ($12K Harness, $18K engineering, $10.5K building, ~$40.5K savings). Harness fee ~$1,500/month. Two-pronged: congregational giving + external grants/sponsorships.',
  },
  {
    id: 'seed-14',
    title: 'Elevator Emergency Phone (Ooma AirDial)',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Technology', 'SafetySanctuary'],
    assignedTo: 'Bart Arther',
    firstRaisedDate: '2026-02-17',
    notes:
      'Approved unanimously Mar 2026 ($55/month + $375 install, dual-path, 16hr battery). Contract stalled on vendor side over address correction.',
  },
  {
    id: 'seed-15',
    title: 'Second Floor Water Fountain',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: 'Karl Leymann, Art Craddock',
    firstRaisedDate: '2026-02-17',
    notes:
      'Repair abandoned after third component (cooler) failed. Replacement $800-$1,000. Art to raise with Finance Committee for CD fund allocation.',
  },
  {
    id: 'seed-16',
    title: 'Soffit Repair and Painting',
    status: 'Closed',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: 'Alberto',
    firstRaisedDate: '2026-01-20',
    closedDate: '2026-04-21',
    closedReason:
      "Project complete. Alberto completed main building soffits and children's wing canopy plywood.",
    notes:
      "Follow-up item: cracked sheeting above children's wing canopy leaking (tar patch on men's group list).",
  },
  {
    id: 'seed-17',
    title: 'K-Mac Electrical Invoice',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Budget', 'Vendors'],
    assignedTo: 'Bill Camp',
    firstRaisedDate: '2026-01-20',
    notes:
      'Original ~$22K, resubmitted $19K, paid $12K, balance ~$7K in dispute. Bill requesting itemized change order descriptions; offered split-the-difference.',
  },
  {
    id: 'seed-18',
    title: 'CE Mitchell Summer Coding Camp',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['FacilityUse'],
    assignedTo: 'Art Craddock',
    firstRaisedDate: '2026-03-17',
    notes:
      'Approved unanimously. Mon-Thu 9 AM-3 PM, June 8 - July 16, up to 20 students. Suspended during VBS week. Key access being coordinated, insurance clarification pending.',
  },
  {
    id: 'seed-19',
    title: 'Bradford Pear Removal',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Grounds'],
    assignedTo: 'Bart Arther, Paul Wilkerson',
    firstRaisedDate: '2026-04-21',
    notes:
      "Norfolk Southern verbally non-objecting; written confirmation required before work begins. May involve Douglas County DOT or men's group with rented chipper.",
  },
  {
    id: 'seed-20',
    title: 'Third Floor / Sanctuary Heat - Return Piping Failure',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['HVAC', 'Building'],
    assignedTo: 'Art Craddock, Karl Leymann',
    firstRaisedDate: '2026-04-21',
    notes:
      'Boiler shut down/drained. No heat to 3rd floor or sanctuary; AC unaffected. No immediate repair (system will be replaced under HVAC project). Karl proposed isolating 3rd floor return. Space heaters available as winter backup.',
  },
  {
    id: 'seed-21',
    title: 'Roof Inspection',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: 'Art Craddock',
    firstRaisedDate: '2026-04-21',
    notes:
      'Alberto observed bubbling/aging shingles, offered introduction to roofing contractor. Insurance-based job possible.',
  },
  {
    id: 'seed-22',
    title: 'Fellowship Hall Kitchen Door - Water Intrusion',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: "Men's Group",
    firstRaisedDate: '2026-04-21',
    notes:
      'Water observed under entry rug despite no rain. Possible sources: hot water heater, ice maker, below-floor leak.',
  },
  {
    id: 'seed-23',
    title: 'Shed Cleanout',
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building', 'Grounds'],
    assignedTo: 'Art Craddock, Kevin Livingston',
    firstRaisedDate: '2025-10-21',
    notes:
      "Art and Kevin meeting Saturday to sort contents. Puppetry materials to Ghana via Kwame's container.",
  },
  {
    id: 'seed-24',
    title: "Children's Wing Canopy - Tar Patch",
    status: 'Open',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Building'],
    assignedTo: "Men's Group",
    firstRaisedDate: '2026-04-21',
    notes: '1-2 gallons tar patch needed for cracked sheeting above newly-replaced plywood.',
  },
  {
    id: 'seed-25',
    title: 'Cross Lights',
    status: 'Closed',
    standing: false,
    defaultSection: 'Auto',
    tags: [],
    closedDate: '2025-10-21',
    closedReason: 'Installation complete.',
  },
  {
    id: 'seed-26',
    title: 'Sanctuary Carpet',
    status: 'Closed',
    standing: false,
    defaultSection: 'Auto',
    tags: [],
    closedDate: '2025-11-18',
    closedReason: "Installation complete; Men's Group funded.",
  },
  {
    id: 'seed-27',
    title: '2026 Budget',
    status: 'Closed',
    standing: false,
    defaultSection: 'Auto',
    tags: ['Budget', 'Finance'],
    closedDate: '2025-12-16',
    closedReason: 'Approved at special meeting (~$121,700).',
  },
  {
    id: 'seed-28',
    title: 'Next Step Learning Academy Daycare Proposal',
    status: 'Declined',
    standing: false,
    defaultSection: 'Auto',
    tags: ['FacilityUse'],
    closedDate: '2026-03-17',
    closedReason: 'Proposal declined - septic, insurance, and programming conflicts.',
  },
];
